### ISSUE TITLE
Modify git workflows to trigger upon action within specific folders/files

### ISSUE THREAD

**Issue by shawngerrard** [asterion-digital/asterion-as-code#20]
We need our git CI workflows to trigger when actions occur (e.g - push, pr) over specific files/folders (e.g `infra-aws`) rather than when these actions occur over the entire repository. This will ensure that in our mono-repo implementation, the git workflows will only trigger when necessary.

**Comment by jmhbnz** [comment]
I'm on the fence on this one, there is a counter argument that having for example both `org-asterion` and `infra-aws` run (in that order) every time the workflows run, is actually a good thing to enforce the desired state of both our org and infra.

This would detect and remediate any drift that could occur over time.

Is it just for performance reasons that you're suggesting we only run things that change in the code?

**Comment by shawngerrard** [comment]
I think implementing pulumi destroy upon flag or end of workflow will cover off the requirement. The original rationale was to avoid using aws resources outside of the working stacks (E.G in a dev environment), but your counter suggestion makes sense.
