### ISSUE TITLE
Move aws accounts into a holding org unit on pulumi destroy of org-asterion

### ISSUE THREAD

**Issue by shawngerrard** [asterion-digital/asterion-as-code#22]
When destroying the pulumi stack for `org-asterion`, pulumi attempts to move the aws member accounts. This triggers aws to attempt transforming the member accounts into stand-alone accounts, which causes exceptions as these member accounts created through pulumi are missing the proper configurations (such as credit card details) to become stand-alone accounts. The exceptions are currently critical issues to bringing the `org-asterion` stack down.

Duplication/deletion also renders email addresses inert and should be avoided.

I propose that we configure the aws account resources created in `main.py` so that when pulumi destroy is initiated, an aws ou is created in organizations as a holding bay for all accounts to be shifted to prior to destruction.

`main.py` will also need further modification so that when the stack is brought up, the holding bay ou contents are placed into a list and checked so that we reuse these resources instead of creating duplicates. 

The additional benefit here is that we may be able to run some kind of scheduled jobs in the future over resources in this ou for further vetting or for initiating the aws account deletion processes.

**Comment by jmhbnz** [comment]
Good summary @shawngerrard .  I'm not opposed to these changes, however I do see this as very low priority currently.

So longs we can `pulumi up` for `org-asterion` we are good to proceed, this won't be a stack we will be destroying as there are no actual cost incurring resources deployed right?

I would like to see us progressing with #9 next so that we can get our production on premises cluster running.

**Comment by shawngerrard** [comment]
Agree. I think a good compromise would be to provide the pulumi account resources with the `retain on delete` [resource option](https://www.pulumi.com/docs/intro/concepts/resources/options/). This may work, while allowing more "combustible" resources to be destroyed.

**Comment by shawngerrard** [comment]
Closed as changes merged successfully.

Have implemented an account migration process to support streamlining of the development process as per issue #34.
