### ISSUE TITLE
Asterion on-premise infrastructure hardware

### ISSUE THREAD

**Issue by shawngerrard** [asterion-digital/asterion-as-code#32]
As a company, we need to self-host services, and as an initial iteration we're running K3S on raspberry pi's (arm64) with networking and persistent storage.

To set this up, we'll need to make some hardware purchases. These should include:

- [network switch](https://www.pbtech.co.nz/product/SWHNGR1208120/NETGEAR-ProSAFE-GS108PP-8-Port-Gigabit-Unmanaged-P)
- [black patch cables x3 each](https://www.pbtech.co.nz/product/CABDNX0193/Dynamix-PLK-C6A-PP-03m-Cat6-Black-UTP-Patch-Lead-T)
- [red patch cables x3 each](https://www.pbtech.co.nz/product/CABDNX0275/Dynamix-PLR-C6A-PP-03m-Cat6-Red-UTP-Patch-Lead-T56)
- [poe hat](https://www.pbtech.co.nz/product/SEVRBP0350/Raspberry-Pi-Add-On-Board-2021-Updated-Version-PoE)
- [usb3 256gb](https://www.pbtech.co.nz/product/MEMKIC24110/Kingston-DT-MAX-256GB-TypeC-Drive-USB-32-Gen-2-Typ)

**Comment by jmhbnz** [comment]
Moving this issue to todo on our board as I think we should prioritize this. 

Also capturing our team conversation last night lets also diagram the two infrastructure stacks (nonprod & prod) as part of the README for our `infra-rpi` stack.

**Comment by jmhbnz** [comment]
Hey @shawngerrard what date is this hardware scheduled to arrive next week?

**Comment by shawngerrard** [comment]
Order is on its way - due pickup at PBTech Vivian St by 09/06

**Comment by shawngerrard** [comment]
> As a company, we need to self-host services, and as an initial iteration we're running K3S on raspberry pi's (arm64) with networking and persistent storage.
> 
> To set this up, we'll need to make some hardware purchases. These should include:
> 
> * [network switch](https://www.pbtech.co.nz/product/SWHNGR1208120/NETGEAR-ProSAFE-GS108PP-8-Port-Gigabit-Unmanaged-P)
> * [black patch cables x3 each](https://www.pbtech.co.nz/product/CABDNX0193/Dynamix-PLK-C6A-PP-03m-Cat6-Black-UTP-Patch-Lead-T)
> * [red patch cables x3 each](https://www.pbtech.co.nz/product/CABDNX0275/Dynamix-PLR-C6A-PP-03m-Cat6-Red-UTP-Patch-Lead-T56)
> * [poe hat](https://www.pbtech.co.nz/product/SEVRBP0350/Raspberry-Pi-Add-On-Board-2021-Updated-Version-PoE)
> * [usb3 256gb](https://www.pbtech.co.nz/product/MEMKIC24110/Kingston-DT-MAX-256GB-TypeC-Drive-USB-32-Gen-2-Typ)

These items have been purchased and installed.

IIRC, from the discussion I believe we landed on a 2 x 6-node (rpi) clusters (1 each for non-prod and prod environments), with 1:1 ratio of server to agent nodes.

If this is the case, we will need to purchase further raspberry pis in the near future unless there are others we can repurpose. Another issue can be opened to capture this. Closing the current issue.
